#!/bin/bash

dockerTag="latest"
dockerRepository="monsterseppe/iot"
bDockerrun=0

Help()
{
   # Display Help
   echo "This is a script for pulling, running, and updating active dockers"
   echo
   echo "Syntax: scriptTemplate [-h|t|p|r]"
   echo "options:"
   echo "h     Print this Help."
   echo "c     Choose the container to pull or run"
   echo "t     Enter a tag for the docker."
   echo "p     Pull the docker."
   echo "r     Run the docker."
   echo "u     Update the docker"
   echo
}

PullDocker() {
    echo "Pulling docker $dockerRepository:$dockerTag"
    docker pull $dockerRepository:$dockerTag
}

CheckContainerID(){
container_id=$(docker ps --filter "ancestor=$dockerRepository:$dockerTag" --format "{{.ID}}")
}

StopDocker(){
    if [ -n "$container_id" ]; then
        echo "stopping container with id: $container_id"
        docker stop $container_id
    fi
}

UpdateDocker(){
    PullDocker
    CheckContainerID
    StopDocker
}

while getopts ":hc:t:pru" option; do
    case $option in
        h) # Display Help
            Help
            exit;;
        t) # Option with argument
            dockerRepository="$OPTARG"
            ;;
        t) # Option with argument
            dockerTag="$OPTARG"
            ;;
        p) # PullDocker
            PullDocker
            ;;
        u) #UpdateDocker
            UpdateDocker
            bDockerrun=1
            ;;
        r) #RunDocker
            bDockerrun=1
            ;;
        \?) # Invalid option
            echo "Error: Invalid option"
            exit;;
    esac
done

if [ $bDockerrun = 1 ]; then
    echo "Running docker $dockerRepository:$dockerTag"
    docker run --privileged --device=/dev/spidev0.0:/dev/spidev0.0 $dockerRepository:$dockerTag
fi
