name: ci

on:
  push:
    branches:
      - Docker-Dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up API Key
        run: |
          echo ${{ secrets.API_KEY }}> secretfile.txt
          echo "File content: $(cat my_file.txt)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          push: true
          platforms: linux/arm64/v8
          tags: ${{ secrets.DOCKER_USERNAME }}/iot:latest