name: ci

on:
  push:
    branches:
      - Docker-Dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          # Set up the API_KEY environment variable from the secret
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up API Key
        run: | 
            echo "${API_KEY}" > secretfile.txt
            echo "$pwd/secretfile.txt"
            echo "File content: $(cat secretfile.txt)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          secret-files: API=secretfile.txt
          context: ./Docker
          push: true
          platforms: linux/arm64/v8
          tags: ${{ secrets.DOCKER_USERNAME }}/iot:latest